echo "Current Free memory"
top -l 1 | grep PhysMem: | awk '{print $10}'

echo "processes will be send a -2 signal first"

sudo killall -2 "AAM Updates Notifier"
sudo killall -2 "App Store"
sudo killall -2 "BitTorrent Sync"
sudo killall -2 "Calculator"
sudo killall -2 "Calendar"
sudo killall -2 "ccc_helper"
sudo killall -2 "ccc_helper"
sudo killall -2 "Chicken of the VNC"
sudo killall -2 "CVMCompiler"
sudo killall -2 "CVMCompiler"
sudo killall -2 "CVMServer"
sudo killall -2 "Dropbox"
sudo killall -2 "Google Chrome Helper"
sudo killall -2 "Google Chrome"
sudo killall -2 "Google Drive"
sudo killall -2 "iTunes Helper"
sudo killall -2 "macfusionAgent"
sudo killall -2 "maspushagent"
sudo killall -2 "mDNSResponder"
sudo killall -2 "Microsoft AU Daemon"
sudo killall -2 "Microsoft Database Daemon"
sudo killall -2 "Microsoft Document Connection"
sudo killall -2 "Microsoft Excel"
sudo killall -2 "Microsoft Lync"
sudo killall -2 "Microsoft Outlook"
sudo killall -2 "Microsoft PowerPoint"
sudo killall -2 "Microsoft Word"
sudo killall -2 "Notes"
sudo killall -2 "Notification Center"
sudo killall -2 "Photo Booth"
sudo killall -2 "Reminders"
sudo killall -2 "Safari Web Content"
sudo killall -2 "Safari"
sudo killall -2 "SpotifyWebHelper"
sudo killall -2 "Stickies"
sudo killall -2 "storeagent"
sudo killall -2 "System Preferences"
#sudo killall -2 "TextWrangler"
sudo killall -2 "TeamViewer"

sudo killall -2 "Viber"


echo "... and now the -v"
echo




sudo killall -v "AAM Updates Notifier"
sudo killall -v "App Store"
sudo killall -v "BitTorrent Sync"
sudo killall -v "Calculator"
sudo killall -v "Calendar"
sudo killall -v "ccc_helper"
sudo killall -v "ccc_helper"
sudo killall -v "Chicken of the VNC"
sudo killall -v "CVMCompiler"
sudo killall -v "CVMCompiler"
sudo killall -v "CVMServer"
sudo killall -v "Dropbox"
sudo killall -v "Google Chrome Helper"
sudo killall -v "Google Chrome"
sudo killall -v "Google Drive"
sudo killall -v "iTunes Helper"
sudo killall -v "macfusionAgent"
sudo killall -v "maspushagent"
sudo killall -v "mDNSResponder"
sudo killall -v "Microsoft AU Daemon"
sudo killall -v "Microsoft Database Daemon"
sudo killall -v "Microsoft Document Connection"
sudo killall -v "Microsoft Excel"
sudo killall -v "Microsoft Lync"
sudo killall -v "Microsoft Outlook"
sudo killall -v "Microsoft PowerPoint"
sudo killall -v "Microsoft Word"
sudo killall -v "Notes"
sudo killall -v "Notification Center"
sudo killall -v "Photo Booth"
sudo killall -v "Reminders"
sudo killall -v "Safari Web Content"
sudo killall -v "Safari"
sudo killall -v "SpotifyWebHelper"
sudo killall -v "Stickies"
sudo killall -v "storeagent"
sudo killall -v "System Preferences"
#sudo killall -v "TextWrangler"
sudo killall -v "Viber"


sleep 3
echo "and now the -9 in 3 seconds!!!"

sudo killall -9 "AAM Updates Notifier"
sudo killall -9 "App Store"
sudo killall -9 "BitTorrent Sync"
sudo killall -9 "Calculator"
sudo killall -9 "Calendar"
sudo killall -9 "ccc_helper"
sudo killall -9 "ccc_helper"
sudo killall -9 "Chicken of the VNC"
sudo killall -9 "CVMCompiler"
sudo killall -9 "CVMCompiler"
sudo killall -9 "CVMServer"
sudo killall -9 "Dropbox"
sudo killall -9 "Google Chrome Helper"
sudo killall -9 "Google Chrome"
sudo killall -9 "Google Drive"
sudo killall -9 "iTunes Helper"
sudo killall -9 "macfusionAgent"
sudo killall -9 "maspushagent"
sudo killall -9 "mDNSResponder"
sudo killall -9 "Microsoft AU Daemon"
sudo killall -9 "Microsoft Database Daemon"
sudo killall -9 "Microsoft Document Connection"
sudo killall -9 "Microsoft Excel"
sudo killall -9 "Microsoft Lync"
sudo killall -9 "Microsoft Outlook"
sudo killall -9 "Microsoft PowerPoint"
sudo killall -9 "Microsoft Word"
sudo killall -9 "Notes"
sudo killall -9 "Notification Center"
sudo killall -9 "Photo Booth"
sudo killall -9 "Reminders"
sudo killall -9 "Safari Web Content"
sudo killall -9 "Safari"
sudo killall -9 "SpotifyWebHelper"
sudo killall -9 "Stickies"
sudo killall -9 "storeagent"
sudo killall -9 "System Preferences"
#sudo killall -9 "TextWrangler"
sudo killall -9 "Viber"
 

echo "Current Free memory"
top -l 1 | grep PhysMem: | awk '{print $10}'

echo
echo "Closing in 3 secs
sleep 3
